#!/usr/bin/env bash
# This script displays Holberton School 10 times using while loop, on 9th iteration print hi on new line
i=1
WORD="Holberton School"
while [ $i -le 10 ]
do
	echo "$WORD"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	(( i++ ))
done
