#!/usr/bin/env bash
# Script that show if file exist, if its empty or if is a file or dir
STR="holbertonschool"
if [ -e "$STR" ]
then
	echo "$STR file exists"
	if [ -s "$STR" ]
	then
		echo "$STR file is not empty"
	else
		echo "$STR file is empty"
	fi

	if [ -f "$STR" ]
	then
		echo "$STR is a regular file"
	fi
else
	echo "$STR file does not exist"
fi
