#!/usr/bin/env bash
# configure nginx
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf | chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start